services:
  - type: web
    name: bus-tracking-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    outputDirectory: frontend/dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: VITE_ADMIN_EMAILS
        sync: false
      - key: VITE_API_URL
        sync: false
      - key: VITE_WEBSOCKET_URL
        sync: false
