version: '3.8'

services:
  bus-tracking-system:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bus-tracking-system
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - ADMIN_EMAILS=${ADMIN_EMAILS}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - bus-tracking-network

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: bus-tracking-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - bus-tracking-system
    restart: unless-stopped
    networks:
      - bus-tracking-network

networks:
  bus-tracking-network:
    driver: bridge

volumes:
  logs:
