version: '3.8'

services:
  # Backend Service (Development)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: builder
    container_name: bus-tracking-backend-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - CORS_ORIGIN=http://localhost:5173,http://localhost:3000,https://ganpat-bts.netlify.app
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=1000
      - LOG_LEVEL=debug
      - ENABLE_DEBUG_LOGS=true
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped
    command: npm run dev
    networks:
      - bus-tracking-network

networks:
  bus-tracking-network:
    driver: bridge
