[build]
  # Build command for Vite from frontend directory
  command = "cd frontend && npm run build"
  # Output directory for the built files
  publish = "frontend/dist"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache CSS and JS files
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables for local backend
[context.production.environment]
  VITE_API_URL = "http://localhost:3000"
  VITE_WEBSOCKET_URL = "ws://localhost:3000"

[context.deploy-preview.environment]
  VITE_API_URL = "http://localhost:3000"
  VITE_WEBSOCKET_URL = "ws://localhost:3000"

[context.branch-deploy.environment]
  VITE_API_URL = "http://localhost:3000"
  VITE_WEBSOCKET_URL = "ws://localhost:3000"
