services:
  # Backend Service
  - type: web
    name: bus-tracking-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_EMAILS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: "3000"

  # Frontend Service (Static Site)
  - type: static
    name: bus-tracking-frontend
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    outputDirectory: dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: VITE_ADMIN_EMAILS
        sync: false
      - key: VITE_API_URL
        sync: false
      - key: VITE_WEBSOCKET_URL
        sync: false
