services:
  - type: web
    name: bus-tracking-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run build && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: ADMIN_EMAILS
        sync: false
